/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package kata.simple;

public class App {

    public static void main(String[] args) {
        System.out.println("Graphical interface in future implementation");
    }
}
