/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package kata.simple;

import org.junit.jupiter.api.Test;

import kata.simple.entityKata.Car;
import kata.simple.entityKata.LocationKata;
import kata.simple.entityKata.Stock;
import kata.simple.enumKata.Precedence;
import kata.simple.enumKata.StatusCar;
import kata.simple.enumKata.TypeCar;

import static org.junit.jupiter.api.Assertions.*;

class ClientTest {
    @Test 
    public void create_createCarWithValidValues_carCreated() {
        Car car = Car.create(1, TypeCar.GASOLINE, 2018, 10000.0, Precedence.JAPAN);
        assertEquals(1, car.getId());
        assertEquals(2018, car.getModel());
        assertEquals(Precedence.JAPAN, car.getPrecedence());        assertEquals(10000.0, car.getPrice());
        assertEquals(10000.0, car.getPrice());
        assertEquals(TypeCar.GASOLINE, car.getType());
    }

    @Test
    public void toString_createCarWithValidValues_carToString() {
        Car car = Car.create(1, TypeCar.GASOLINE, 2018, 10000.0, Precedence.JAPAN);
        assertEquals("Car{id=1, type=GASOLINE, model=2018, price=10000.0, precedence=JAPAN}", car.toString());
    }

    @Test
    public void create_createLocationKataWithValidValues_locationKataCreated(){
        LocationKata locationKat = LocationKata.create(StatusCar.SENT, "A", "B");
        assertEquals(StatusCar.SENT, locationKat.getStatus());
        assertEquals("A", locationKat.getOrigin());
        assertEquals("B", locationKat.getDestination());
    }

    @Test
    public void toString_createLocationKataWithValidValues_locationKataToString(){
        LocationKata locationKat = LocationKata.create(StatusCar.SENT, "A", "B");
        assertEquals("LocationKata{status=SENT, origin='A', destination='B'}", locationKat.toString());
    }

    @Test
    public void create_createStockWithValidValues_stockCreated(){
        Car car = Car.create(1, TypeCar.GASOLINE, 2018, 10000.0, Precedence.JAPAN);
        Stock stock = Stock.create(car, 10);
        assertEquals(car, stock.getCar());
        assertEquals(10, stock.getQuantity());
    }

    @Test
    public void toString_createStockWithValidValues_stockToString(){
        Car car = Car.create(1, TypeCar.GASOLINE, 2018, 10000.0, Precedence.JAPAN);
        Stock stock = Stock.create(car, 10);
        assertEquals("Stock{car=Car{id=1, type=GASOLINE, model=2018, price=10000.0, precedence=JAPAN}, quantity=10}", stock.toString());
    }
}
