/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package kata.simple;

import org.junit.jupiter.api.Test;

import kata.simple.entityKata.Car;
import kata.simple.entityKata.LocationKata;
import kata.simple.entityKata.Stock;
import kata.simple.enumKata.Precedence;
import kata.simple.enumKata.StatusCar;
import kata.simple.enumKata.TypeCar;

import static org.junit.jupiter.api.Assertions.*;

class ClientTest {
    @Test 
    public void create_createCarWithValidValues_carCreated() {
        Car car =  new Car.Builder().setId(1).setType(TypeCar.GASOLINE).setModel(2018).setPrice(10000.0).setPrecedence(Precedence.JAPAN).build();
        assertEquals(1, car.getId());
        assertEquals(2018, car.getModel());
        assertEquals(Precedence.JAPAN, car.getPrecedence());        assertEquals(10000.0, car.getPrice());
        assertEquals(10000.0, car.getPrice());
        assertEquals(TypeCar.GASOLINE, car.getType());
    }

    @Test
    public void toString_createCarWithValidValues_carToString() {
        Car car = new Car.Builder().setId(1).setType(TypeCar.GASOLINE).setModel(2018).setPrice(10000.0).setPrecedence(Precedence.JAPAN).build();
        assertEquals("Car{id=1, type=GASOLINE, model=2018, price=10000.0, precedence=JAPAN}", car.toString());
    }

    @Test
    public void create_createLocationKataWithValidValues_locationKataCreated(){
        LocationKata locationKat = new LocationKata.Builder().setStatus(StatusCar.SENT).setOrigin("A").setDestination("B").build();
        assertEquals(StatusCar.SENT, locationKat.getStatus());
        assertEquals("A", locationKat.getOrigin());
        assertEquals("B", locationKat.getDestination());
    }

    @Test
    public void toString_createLocationKataWithValidValues_locationKataToString(){
        LocationKata locationKat = new LocationKata.Builder().setStatus(StatusCar.SENT).setOrigin("A").setDestination("B").build();
        assertEquals("LocationKata{status=SENT, origin='A', destination='B'}", locationKat.toString());
    }

    @Test
    public void create_createStockWithValidValues_stockCreated(){
        Car car = new Car.Builder().setId(1).setType(TypeCar.GASOLINE).setModel(2018).setPrice(10000.0).setPrecedence(Precedence.JAPAN).build();
        Stock stock = new Stock.Builder().setCar(car).setQuantity(10).build();
        assertEquals(car, stock.getCar());
        assertEquals(10, stock.getQuantity());
    }

    @Test
    public void toString_createStockWithValidValues_stockToString(){
        Car car = new Car.Builder().setId(1).setType(TypeCar.GASOLINE).setModel(2018).setPrice(10000.0).setPrecedence(Precedence.JAPAN).build();
        Stock stock = new Stock.Builder().setCar(car).setQuantity(10).build();
        assertEquals("Stock{car=Car{id=1, type=GASOLINE, model=2018, price=10000.0, precedence=JAPAN}, quantity=10}", stock.toString());
    }
}
